FROM node:18

WORKDIR /app

COPY package.json package-lock.json /app/
RUN npm install --legacy-peer-deps

COPY . /app/

ARG VITE_CLIENT_ID
ARG VITE_REQUEST_URL
ARG VITE_WS_URL
ARG PORT 

ENV PORT=$PORT
ENV VITE_CLIENT_ID=$VITE_CLIENT_ID
ENV VITE_REQUEST_URL=$VITE_REQUEST_URL
ENV VITE_WS_URL=$VITE_WS_URL
RUN npm run build 

EXPOSE 4173

CMD ["npm","run","preview","--","--host"]
