services:
  # Django Backend
  backend:
    build:
      network: host
      context: ./backend
      dockerfile: Dockerfile
    container_name: cricket_scorer_backend
    volumes:
      - ./backend:/app
    command: >
      bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DEBUG=1
    depends_on:
      - cricketscorer-db
    networks:
      - mynetwork

  # React Frontend
  frontend:
    build:
      network: host
      args:
        - VITE_CLIENT_ID=${VITE_CLIENT_ID}
        - VITE_REQUEST_URL=${VITE_REQUEST_URL}
        - VITE_WS_URL=${VITE_WS_URL}
        - PORT=5173
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - mynetwork

  # PostgreSQL Database
  cricketscorer-db:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  #redis setup
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
